[build]
  command = "git submodule update --init --depth=1 && npm ci && npm run build"
  publish = "dist"
  ignore_nvm = true   # Added to ignore .nvmrc

# Environment variables
[build.environment]
  NODE_VERSION = "18.19.0"  # Specify a specific version that works with Vite
  NPM_VERSION = "9"
  PYTHON_VERSION = "3.9"
  NODE_OPTIONS = "--max-old-space-size=4096"  # Give Node more memory for the build
  # Add your actual API keys in the Netlify UI, not here for security reasons
  # VITE_OPENAI_API_KEY = "your_api_key_here"
  GIT_LFS_ENABLED = "true"
  # Speed up the build
  CI = "true"
  NPM_CONFIG_PRODUCTION = "false"

[build.processing]
  skip_processing = false

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=0, must-revalidate"

# Set proper headers for JavaScript modules
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"